// Widgets

export const WIDGET_LIST_REQUESTED = `WIDGET_LIST_REQUESTED`;
export const WIDGET_LIST_SUCCEEDED = `WIDGET_LIST_SUCCEEDED`;
export const WIDGET_LIST_FAILED = `WIDGET_LIST_FAILED`;
export const WIDGET_LIST_RESET = `WIDGET_LIST_RESET`;

export const WIDGET_ITEM_REQUESTED = `WIDGET_ITEM_REQUESTED`;
export const WIDGET_ITEM_SUCCEEDED = `WIDGET_ITEM_SUCCEEDED`;
export const WIDGET_ITEM_FAILED = `WIDGET_ITEM_FAILED`;

export const WIDGET_SET_ITEM = `WIDGET_SET_ITEM`;

export const WIDGET_SET_MODAL = `WIDGET_SET_MODAL`;
export const WIDGET_SET_MODAL_SUBMITTING_STATUS = `WIDGET_SET_MODAL_SUBMITTING_STATUS`;
export const WIDGET_RESET_MODAL = `WIDGET_RESET_MODAL`;
export const WIDGET_SHOW_CREATION_MODAL_AFTER_CREATING = `WIDGET_SHOW_CREATION_MODAL_AFTER_CREATING`;

export const WIDGET_SET_ERROR = `WIDGET_SET_ERROR`;
export const WIDGET_RESET_ERROR = `WIDGET_RESET_ERROR`;

export const WIDGET_SET_MODAL_ERROR = `WIDGET_SET_MODAL_ERROR`;
export const WIDGET_RESET_MODAL_ERROR = `WIDGET_RESET_MODAL_ERROR`;

export const WIDGET_CREATE_REQUESTED = `WIDGET_CREATE_REQUESTED`;
export const WIDGET_CREATE_SUCCEEDED = `WIDGET_CREATE_SUCCEEDED`;

export const WIDGET_REMOVE_REQUESTED = `WIDGET_REMOVE_REQUESTED`;
export const WIDGET_REMOVE_SUCCEEDED = `WIDGET_REMOVE_SUCCEEDED`;

export const WIDGET_LIST_ITEM_UPDATE_REQUESTED = `WIDGET_LIST_ITEM_UPDATE_REQUESTED`;
export const WIDGET_LIST_ITEM_UPDATE_SUCCEEDED = `WIDGET_LIST_ITEM_UPDATE_SUCCEEDED`;

export const WIDGET_ITEM_UPDATE_REQUESTED = `WIDGET_ITEM_UPDATE_REQUESTED`;
export const WIDGET_ITEM_UPDATE_SUCCEEDED = `WIDGET_ITEM_UPDATE_SUCCEEDED`;

export const WIDGET_SET_PAGE = `WIDGET_SET_PAGE`;

export const WIDGET_SET_ANY_DATA = `WIDGET_SET_ANY_DATA`;

// Proxies

export const PROXY_CHECK_REQUESTED = `PROXY_CHECK_REQUESTED`;
export const PROXY_CHECK_SUCCEEDED = `PROXY_CHECK_SUCCEEDED`;
export const PROXY_CHECK_FAILED = `PROXY_CHECK_FAILED`;

// Wallets

export const MARK_WALLET_AS_ACTIVE_REQUESTED = `MARK_WALLET_AS_ACTIVE_REQUESTED`;
export const MARK_WALLET_AS_ACTIVE_SUCCEEDED = `MARK_WALLET_AS_ACTIVE_SUCCEEDED`;
export const MARK_WALLET_AS_ACTIVE_FAILED = `MARK_WALLET_AS_ACTIVE_FAILED`;

export const RESET_WALLET_SELECTION = `RESET_WALLET_SELECTION`;

// Transactions

export const DOWNLOAD_TRANSACTION_CSV_LIST_REQUESTED = `DOWNLOAD_TRANSACTION_CSV_LIST_REQUESTED`;
export const DOWNLOAD_TRANSACTION_CSV_LIST_SUCCEEDED = `DOWNLOAD_TRANSACTION_CSV_LIST_SUCCEEDED`;
export const DOWNLOAD_TRANSACTION_CSV_LIST_FAILED = `DOWNLOAD_TRANSACTION_CSV_LIST_FAILED`;

// Auth

export const LOGIN_REQUESTED = `LOGIN_REQUESTED`;
export const LOGIN_SUCCEEDED = `LOGIN_SUCCEEDED`;

export const LOGOUT_REQUESTED = `LOGOUT_REQUESTED`;
export const LOGOUT_SUCCEEDED = `LOGOUT_SUCCEEDED`;

export const AUTH_ERROR = `AUTH_ERROR`;

export const AUTH_CHECK_REQUESTED = `AUTH_CHECK_REQUESTED`;
export const AUTH_CHECK_SUCCEEDED = `AUTH_CHECK_SUCCEEDED`;

export const SET_TOKEN = `SET_TOKEN`;

export const REFRESH_TOKEN_REQUESTED = `REFRESH_TOKEN_REQUESTED`;
export const REFRESH_TOKEN_SUCCEEDED = `REFRESH_TOKEN_SUCCEEDED`;
export const REFRESH_TOKEN_FAILED = `REFRESH_TOKEN_FAILED`;

export const CHANGE_PASSWORD_REQUESTED = `CHANGE_PASSWORD_REQUESTED`;

// Dashboard

export const DASHBOARD_DATA_REQUESTED = `DASHBOARD_DATA_REQUESTED`;
export const DASHBOARD_DATA_SUCCEEDED = `DASHBOARD_DATA_SUCCEEDED`;

export const DASHBOARD_LOADED_ALL_DATA = `DASHBOARD_LOADED_ALL_DATA`;
export const DASHBOARD_RESET = `DASHBOARD_RESET`;

// Wallet paytm

export const WALLET_PAYTM_CODE_CONFIRMATION = `WALLET_PAYTM_CODE_CONFIRMATION`;
